all:
	gcc -Wall -ansi -o incrementar_numero_hijo incrementar_numero_hijo.c
	gcc -Wall -ansi -o pulsar_ctrlc pulsar_ctrlc.c
	gcc -Wall -ansi -o alarm alarma.c

clean:
	rm -f incrementar_numero_hijo pulsar_ctrlc alarma
