
# This is a template Makefile generated by rpcgen

# Parameters

CLIENT = client
SERVER = server

SOURCES_CLNT.c = client.c
SOURCES_CLNT.h = 
SOURCES_SVC.c = server.c
SOURCES_SVC.h = 
SOURCES.x = text.x

TARGETS_SVC.c = text_svc.c text_xdr.c 
TARGETS_CLNT.c = text_clnt.c text_xdr.c 
TARGETS = text.h text_xdr.c text_clnt.c text_svc.c

OBJECTS_CLNT = $(SOURCES_CLNT.c:%.c=%.o) $(TARGETS_CLNT.c:%.c=%.o)
OBJECTS_SVC = $(SOURCES_SVC.c:%.c=%.o) $(TARGETS_SVC.c:%.c=%.o)
# Compiler flags 

CPPFLAGS += -D_REENTRANT -DDEBUG
CFLAGS += -g 
LDLIBS += -lnsl -lpthread 
RPCGENFLAGS = -M

# Targets 

all : $(CLIENT) $(SERVER)

$(TARGETS) : $(SOURCES.x) 
	rpcgen $(RPCGENFLAGS) $(SOURCES.x)

$(OBJECTS_CLNT) : $(SOURCES_CLNT.c) $(SOURCES_CLNT.h) $(TARGETS_CLNT.c) 

$(OBJECTS_SVC) : $(SOURCES_SVC.c) $(SOURCES_SVC.h) $(TARGETS_SVC.c) 

$(CLIENT) : $(OBJECTS_CLNT) 
	$(LINK.c) -o $(CLIENT) $(OBJECTS_CLNT) $(LDLIBS) 

$(SERVER) : $(OBJECTS_SVC) 
	$(LINK.c) -o $(SERVER) $(OBJECTS_SVC) $(LDLIBS)

clean:
	$(RM) core $(TARGETS) $(OBJECTS_CLNT) $(OBJECTS_SVC) $(CLIENT) $(SERVER)

