all:
	gcc -Wall -ansi -o combine combine.c 
	gcc -Wall -ansi -o split split.c
	gcc -Wall -ansi -o statistics statistics.c 
	gcc -Wall -ansi -o text2bin text2bin.c
	gcc -Wall -ansi -o bin2text bin2text.c

clean:
	rm -f combine split statistics text2bin bin2text
