all:
	gcc -lpthread -o argvsint-1 argvsint-1.c
	gcc -lpthread -o joinconvalor-1 joinconvalor-1.c
	gcc -lpthread -lm -o numero-piParam numero-piParam.c
	gcc -lpthread -o ejercicio ejercicio.c

clean:
	rm -f argvsint-1 joinconvalor-1 numero-piParam ejercicio
